version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=project4.settings
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_HOST=db  # Points to the 'db' service

    depends_on:
      - db  # Ensure the database service starts before the web service

  db:
    image: postgres:latest  # Pull the latest PostgreSQL image
    container_name: postgres_container
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: securepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
    ports:
      - "5432:5432"  # Expose the database for external access (optional)

volumes:
  postgres_data:
