# Generated by Django 4.2.16 on 2024-12-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_Reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to='network.userprofile'),
        ),
    ]
